name = "talker-mvp"
main = "_worker.js"
compatibility_date = "2023-05-18"

[site]
bucket = "./dist"

[build]
command = "npm run build"
publish = "dist"

[env.production]
name = "talker-mvp"
route = "ocutalk.com/*"

[env.staging]
name = "talker-mvp-staging"
route = "staging.ocutalk.com/*"
